id: P9D98ECDE
initial_creation_type: ocr
source_metadata:
  volumes:
    8b6b1d102082488a91328de6608d9482:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཡི་གེ་བརྒྱ་པ།
      total_pages: 1605
      volume_number: 57
